services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shree-graphics-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shree-graphics-frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped