"use client";
import Link from "next/link";
import { ArrowRight, Wrench } from "lucide-react";
import { motion } from "framer-motion";
import Badge from "@/components/public/ui/Badge";
import Button from "@/components/public/ui/Button";
import Container from "@/components/public/ui/Container";
import GlassCard from "@/components/public/ui/GlassCard";
export default function SparePartsHero(){return <section className="relative isolate overflow-hidden bg-[#0B1220] pb-20 pt-32 sm:pt-40"><div aria-hidden className="absolute -left-28 top-24 h-[30rem] w-[30rem] rounded-full bg-[#4274D9]/22 blur-[140px]"/><div aria-hidden className="absolute right-[-8rem] bottom-0 h-[28rem] w-[28rem] rounded-full bg-[#D3C09A]/10 blur-[140px]"/><Container className="relative z-10 grid items-center gap-12 lg:grid-cols-[1fr_390px]"><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}}><Badge>Parts & support</Badge><h1 className="mt-6 font-display text-6xl font-black leading-[.88] tracking-[-.055em] sm:text-7xl lg:text-8xl">Keep your machine <span className="bg-gradient-to-r from-[#95CCDD] to-[#4274D9] bg-clip-text text-transparent">running.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Genuine and replacement components for Shree Graphics machinery. Tell us what your machine needs and our team will help identify the right part or replacement requirement.</p><div className="mt-9 flex flex-wrap gap-3"><Button href="#parts-request">Request a Part</Button><Button href="#parts-range" variant="secondary">Explore Parts</Button></div></motion.div><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.12}}><GlassCard className="rounded-3xl p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#4274D9]/20 text-[#95CCDD]"><Wrench size={19}/></span><div><p className="text-[10px] uppercase tracking-[.18em] text-[#95CCDD]">Parts Desk</p><p className="mt-1 font-semibold text-white">SG / Spares</p></div></div><div className="mt-7 space-y-2">{["Machine Parts","Replacement Components","Custom Requirements"].map((item,i)=><div key={item} className="flex items-center justify-between rounded-2xl border border-white/10 px-4 py-4"><span className="text-xs text-[#95CCDD]">0{i+1}</span><span className="text-sm text-slate-200">{item}</span><ArrowRight size={15} className="text-slate-500"/></div>)}</div></GlassCard></motion.div></Container></section>}
