'use client';

import { ChangeEvent, DragEvent, useEffect, useState } from 'react';
import { ImagePlus, Loader2, Pencil, Plus, Trash2, Video } from 'lucide-react';
import type { GalleryCategory, GalleryEvent, GalleryItem } from '@/lib/types';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:5000';
const categories: Array<{ value: GalleryCategory; label: string }> = [
  { value: 'machine', label: 'Machines' }, { value: 'airshaft', label: 'Airshafts' },
  { value: 'spare_part', label: 'Spare Parts' }, { value: 'exhibition', label: 'Exhibitions' },
];
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export default function AdminGalleryPage() {
  const [category, setCategory] = useState<GalleryCategory>('machine');
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [events, setEvents] = useState<GalleryEvent[]>([]);
  const [eventId, setEventId] = useState('');
  const [eventName, setEventName] = useState('');
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [message, setMessage] = useState('');

  const loadEvents = async () => { try { const r = await fetch(`${API}/api/gallery/events?admin=true`, { credentials: 'include' }); const b = await r.json(); setEvents(b.data ?? []); } catch { setMessage('Unable to load exhibitions.'); } };
  const load = async () => { setLoading(true); try { let url = `${API}/api/gallery?category=${category}&admin=true`; if (category === 'exhibition' && eventId) url += `&event_id=${eventId}`; const r = await fetch(url, { credentials: 'include' }); const b = await r.json(); setItems(b.data ?? []); } catch { setMessage('Unable to load gallery items.'); } finally { setLoading(false); } };
  useEffect(() => { void loadEvents(); }, []);
  useEffect(() => { if (category !== 'exhibition' || eventId) void load(); else { setItems([]); setLoading(false); } }, [category, eventId]);

  const createEvent = async () => { const name = eventName.trim(); if (!name) return; const r = await fetch(`${API}/api/gallery/events`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, slug: slugify(name), sort_order: events.length }) }); const b = await r.json(); if (!r.ok) { setMessage(b.message ?? 'Could not create event'); return; } setEventName(''); await loadEvents(); setEventId(b.data.id); setMessage(`${name} created. Now upload its media.`); };
  const editEvent = async () => { const current = events.find(e => e.id === eventId); if (!current) return; const name = prompt('Exhibition name', current.name)?.trim(); if (!name) return; const r = await fetch(`${API}/api/gallery/events/${eventId}`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, slug: slugify(name) }) }); if (!r.ok) { setMessage('Could not update exhibition.'); return; } await loadEvents(); setMessage('Exhibition updated.'); };
  const removeEvent = async (id: string) => { if (!confirm('Delete this exhibition and all media inside it?')) return; const r = await fetch(`${API}/api/gallery/events/${id}`, { method: 'DELETE', credentials: 'include' }); if (!r.ok) { setMessage('Could not delete exhibition.'); return; } setEventId(''); await loadEvents(); setItems([]); };
  const upload = async (files: FileList | File[]) => { if (category === 'exhibition' && !eventId) { setMessage('Create or select an exhibition first.'); return; } const selected = Array.from(files).filter(f => f.type.startsWith('image/') || f.type.startsWith('video/')); if (!selected.length) { setMessage('Choose image or video files.'); return; } setUploading(true); setMessage(''); try { const form = new FormData(); selected.forEach(f => form.append('media', f)); const up = await fetch(`${API}/api/uploads/gallery-media`, { method: 'POST', credentials: 'include', body: form }); const body = await up.json(); if (!up.ok) throw new Error(body.message ?? 'Upload failed'); for (const media of body.data) { const created = await fetch(`${API}/api/gallery`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ category, event_id: category === 'exhibition' ? eventId : null, media_type: media.media_type, media_url: media.url, sort_order: items.length }) }); if (!created.ok) throw new Error('Media uploaded but could not be saved'); } setMessage(`${selected.length} file(s) added.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Upload failed'); } finally { setUploading(false); } };
  const remove = async (id: string) => { if (!confirm('Remove this media?')) return; const r = await fetch(`${API}/api/gallery/${id}`, { method: 'DELETE', credentials: 'include' }); if (r.ok) await load(); };

  return <main className="min-h-screen bg-gray-100 px-3 py-5 sm:px-6 sm:py-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Content</p><h1 className="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">Gallery</h1><p className="mt-2 max-w-xl text-sm text-gray-600 sm:text-base">Manage photos and videos shown on the website.</p>
    <div role="tablist" aria-label="Gallery categories" className="mt-6 flex gap-2 overflow-x-auto pb-1 [-webkit-overflow-scrolling:touch] sm:mt-8">{categories.map(c => <button role="tab" aria-selected={category === c.value} key={c.value} onClick={() => { setCategory(c.value); setMessage(''); }} className={`min-h-11 shrink-0 rounded-lg px-4 py-2 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-900 ${category === c.value ? 'bg-gray-900 text-white' : 'bg-white text-gray-600 shadow-sm hover:bg-gray-50'}`}>{c.label}</button>)}</div>
    {category === 'exhibition' && <section aria-label="Exhibition management" className="mt-5 rounded-xl bg-white p-4 shadow-sm sm:mt-6 sm:rounded-2xl sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:gap-4"><div className="min-w-0 flex-1"><label htmlFor="gallery-event" className="text-sm font-semibold text-gray-700">Exhibition event</label><select id="gallery-event" value={eventId} onChange={e => setEventId(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-gray-300 px-3 py-2 text-base"><option value="">Select an exhibition</option>{events.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></div>{eventId && <div className="grid grid-cols-2 gap-2 sm:flex"><button aria-label="Edit exhibition" onClick={() => void editEvent()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-gray-200 px-4 py-2 text-sm font-semibold text-gray-700"><Pencil size={16} />Edit</button><button onClick={() => void removeEvent(eventId)} className="min-h-11 rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-600">Delete</button></div>}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="new-exhibition">New exhibition name</label><input id="new-exhibition" value={eventName} onChange={e => setEventName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void createEvent(); }} placeholder="e.g. PAMEX 2026" className="min-h-11 min-w-0 flex-1 rounded-lg border border-gray-300 px-3 py-2 text-base"/><button onClick={() => void createEvent()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white"><Plus size={16} />Create exhibition</button></div></section>}
    {(category !== 'exhibition' || eventId) && <div onDragEnter={(e: DragEvent) => { e.preventDefault(); setDragging(true); }} onDragOver={e => e.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); void upload(e.dataTransfer.files); }} className={`mt-5 rounded-xl border-2 border-dashed p-6 text-center transition sm:mt-6 sm:rounded-2xl sm:p-12 ${dragging ? 'border-blue-500 bg-blue-50' : 'border-gray-300 bg-white'}`}><ImagePlus className="mx-auto h-9 w-9 text-gray-400 sm:h-10 sm:w-10"/><h2 className="mt-3 text-base font-bold text-gray-900 sm:mt-4 sm:text-lg">Drop images or videos here</h2><p className="mt-1 text-xs text-gray-500 sm:mt-2 sm:text-sm">Tap to select files on mobile. Multiple files supported.</p><label className="mt-5 inline-flex min-h-11 cursor-pointer items-center rounded-lg bg-gray-900 px-5 py-3 text-sm font-semibold text-white"><input aria-label="Select gallery files" className="sr-only" type="file" multiple accept="image/*,video/*" onChange={(e: ChangeEvent<HTMLInputElement>) => { if (e.target.files) void upload(e.target.files); e.target.value = ''; }}/>{uploading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Uploading...</> : 'Select files'}</label></div>}
    {category === 'exhibition' && !eventId && <div className="mt-6 rounded-xl border border-dashed border-gray-300 bg-white px-5 py-12 text-center text-sm text-gray-500 sm:mt-8 sm:rounded-2xl sm:px-6 sm:py-16">Create or select an exhibition to manage its photos and videos.</div>}
    {message && <p aria-live="polite" className="mt-4 rounded-lg bg-white px-3 py-2 text-sm text-gray-700 shadow-sm">{message}</p>}
    {!loading && items.length > 0 && <div className="mt-6 grid grid-cols-1 gap-3 sm:mt-8 sm:grid-cols-2 sm:gap-4 lg:grid-cols-3">{items.map(i => <article key={i.id} className="overflow-hidden rounded-xl bg-white shadow-sm"><div className="relative aspect-video bg-gray-100">{i.media_type === 'video' ? <><video src={i.media_url} className="h-full w-full object-cover" controls playsInline/><span aria-hidden="true" className="absolute left-3 top-3 rounded bg-black/70 p-2 text-white"><Video size={16}/></span></> : <img src={i.media_url} alt={i.title ?? 'Gallery item'} loading="lazy" className="h-full w-full object-cover"/>}</div><div className="flex justify-end p-2"><button aria-label="Delete gallery item" onClick={() => void remove(i.id)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg text-red-600 hover:bg-red-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500"><Trash2 size={18}/></button></div></article>)}</div>}
  </div></main>;
}
