"use client";

import { ArrowRight, Sparkles } from "lucide-react";
import ScrollReveal from "@/components/public/ScrollReveal";

export default function TechnicalStatement() {
  return <section id="philosophy" className="relative overflow-hidden border-y border-[#95CCDD]/20 bg-[linear-gradient(135deg,#0B1220_0%,#101B31_52%,#13213A_100%)] py-20 sm:py-24 lg:py-32">
    <div aria-hidden className="pointer-events-none absolute inset-0 opacity-35" style={{ backgroundImage:"linear-gradient(to right,rgba(149,204,221,.055) 1px,transparent 1px),linear-gradient(to bottom,rgba(149,204,221,.055) 1px,transparent 1px)", backgroundSize:"72px 72px" }} />
    <div aria-hidden className="absolute -right-24 top-1/3 h-[460px] w-[460px] rounded-full bg-[#4274D9]/20 blur-[130px]" />
    <div aria-hidden className="absolute bottom-0 left-0 h-[320px] w-[320px] rounded-full bg-[#F36A21]/10 blur-[120px]" />
    <div className="relative z-10 mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">
      <ScrollReveal><div className="max-w-5xl"><div className="mb-7 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-[#F36A21]/50 bg-[#F36A21]/10"><Sparkles size={15} className="text-[#F36A21]"/></span><span className="font-mono text-[9px] font-bold uppercase tracking-[.22em] text-[#F36A21]">The Shree Graphics approach</span></div><h2 className="font-display text-4xl font-black uppercase leading-[.9] tracking-[-.04em] text-white sm:text-5xl md:text-6xl lg:text-7xl xl:text-[5.6rem]">UPDATING INDUSTRIES<br/><span className="text-[#95CCDD]">WITH THE BEST</span><br/><span className="text-[#F36A21]">TECHNOLOGY.</span></h2><p className="mt-8 max-w-3xl border-l-2 border-[#4274D9] pl-5 text-base leading-7 text-slate-300 sm:mt-10 sm:pl-6 sm:text-lg sm:leading-8">Since 2009, Shree Graphics has focused on practical converting and printing solutions built around real production requirements. With 150+ machines delivered, our approach is to understand the application, engineer the right system and keep customers moving forward with better technology.</p></div></ScrollReveal>
      <ScrollReveal delay={140}><div className="mt-12 grid gap-4 sm:mt-16 sm:grid-cols-3"><div className="rounded-2xl border border-[#95CCDD]/20 bg-[#13213A]/70 p-6"><div className="font-display text-4xl font-black text-[#F36A21]">2009</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[.18em] text-[#95CCDD]/70">Established</div></div><div className="rounded-2xl border border-[#95CCDD]/20 bg-[#13213A]/70 p-6"><div className="font-display text-4xl font-black text-[#F36A21]">150+</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[.18em] text-[#95CCDD]/70">Machines delivered</div></div><div className="rounded-2xl border border-[#95CCDD]/20 bg-[#13213A]/70 p-6"><div className="font-display text-xl font-black uppercase text-white">Best technology</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[.18em] text-[#95CCDD]/70">Built around the application</div></div></div></ScrollReveal>
      <ScrollReveal delay={260}><div className="mt-12 flex flex-col gap-6 border-t border-[#95CCDD]/15 pt-8 sm:mt-16 lg:flex-row lg:items-end lg:justify-between"><blockquote className="max-w-3xl font-display text-2xl font-bold uppercase leading-[.95] text-slate-100 sm:text-3xl lg:text-4xl">Technology should improve the process—not complicate it.</blockquote><a href="/about" className="group inline-flex min-h-11 shrink-0 items-center gap-4 font-mono text-[9px] font-bold uppercase tracking-[.17em] text-[#95CCDD] transition-colors hover:text-white"><span>Our story</span><ArrowRight size={15} className="text-[#F36A21] transition-transform duration-300 group-hover:translate-x-2"/></a></div></ScrollReveal>
    </div>
  </section>;
}
